### ISSUE TITLE
【バグ】レシピが重複していると言われる

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [TeamKun/TeamKUNPluginManager#26]
# 【バグ】レシピが重複していると言われる

## 概要

+ MoneyCraft等の、レシピを追加する系のやつで、2度以上KPMを使用しインストール/アンインストールを繰り返すと、Exception

## エラー

```
[06:18:45] [Server thread/ERROR]: Error occurred while enabling MoneyCraft v1.5.1 (Is it up to date?)
java.lang.IllegalStateException: Duplicate recipe ignored with ID moneycraft:wallet
	at net.minecraft.server.v1_15_R1.CraftingManager.addRecipe(CraftingManager.java:77) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftShapedRecipe.addToCraftingManager(CraftShapedRecipe.java:59) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.addRecipe(CraftServer.java:1226) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.Bukkit.addRecipe(Bukkit.java:728) ~[patched_1.15.2.jar:git-Paper-391]
	at net.kunmc.lab.moneycraft.MoneyCraft.onEnable(MoneyCraft.java:74) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-391]
	at net.kunmc.lab.teamkunpluginmanager.utils.PluginUtil$1.run(PluginUtil.java:514) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1265) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

**Comment by PeyaPeyaPeyang** [comment]
[v2.0](https://github.com/TeamKun/TeamKUNPluginManager/releases/tag/v2.0)により解決しました。
